[database]

driver="mysql"
access="gorse_user:password@tcp(localhost:3306)/gorse_db"

[server]
api_key="Gorse@123"
api_port=8089
dashboard_port=8088

[recommend]

feedback_types=["like","watch","save","search"]

[ranking]
like=3
watch=2
save=4
search=1
